services:

  app:
    build: .
    container_name: notes_app
    environment:
      - DB_USER=postgres
      - DB_PWD=pg---test--password
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=notes_db
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    restart: unless-stopped
    
  db:
    image: postgres:13
    container_name: notes_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg---test--password
      POSTGRES_DB: notes_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: